# Generated by Django 3.0.5 on 2020-05-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercreate',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterModelOptions(
            name='userimages',
            options={'verbose_name': 'UserImage'},
        ),
        migrations.AlterField(
            model_name='usercreate',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
