# Generated by Django 3.0.5 on 2020-05-08 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imageapi', '0002_auto_20200508_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserCreate',
        ),
    ]
